### ISSUE TITLE
Progress bar doesn't update in-place on Windows

### ISSUE THREAD

**Issue by cafreeman** [cheggaaa/pb#78]
Hi there, 

I was wondering if you knew of a way to make the progress bar actually update "in-place" in windows?

On OS X, the progress bar behaves exactly as I'd expect, i.e. It prints the bar to the console and then updates it with each increment.

On Windows, however, a new progress bar just gets re-printed to the screen with each update, so you end up with a screen full of static progress bars, like this:

![image](https://cloud.githubusercontent.com/assets/7971393/15187491/ed098cee-1766-11e6-8efb-f15bf3a14181.png)

I've looked through options and existing issues to see if there's some config option I can use to tweak this, but I haven't found anything so far. Do you have any suggestions?

Thank you!

**Comment by cheggaaa** [comment]
Hi, thanks for reporting!
It's was fixed in #77 
But my bad... I forget to create new release tag.
Tag v1.0.3 created! 
Try to update package ```go get -u gopkg.in/cheggaaa/pb```

**Comment by cafreeman** [comment]
@cheggaaa Thanks for the heads up. Just tried updating and rebuilding but it doesn't appear to have had any effect :( Still seeing the repeated bars

**Comment by cafreeman** [comment]
FWIW, here's the code I'm using to create the bar. Maybe I'm just doing it wrong?

```go
func createProgressBar(response *http.Response) *pb.ProgressBar {
	// Get the response size from the HTTP header for calculating download progress
	responseSize, _ := strconv.Atoi(response.Header.Get("Content-Length"))

	// Create progress bar
	bar := pb.New(int(responseSize)).SetUnits(pb.U_BYTES).SetRefreshRate(time.Millisecond * 10)
	bar.ShowSpeed = true
	bar.ShowTimeLeft = true
	bar.SetWidth(120)

	return bar
}
```

**Comment by cheggaaa** [comment]
@cafreeman just remove ```bar.SetWidth(120)```
